call ppm install DBD::CSV
call ppm install DBD::ODBC
call ppm install DBI
call ppm install DateTime::Format::DateParse
call ppm install Devel::NYTProf
call ppm install Dist::Zilla
call ppm install Dist::Zilla::PluginBundle::Author::LESPEA
call ppm install Exporter::Easy
call ppm install File::HomeDir
call ppm install File::ShareDir
call ppm install File::Slurp
call ppm install Getopt::Long::Descriptive
call ppm install HTML::Tree
call ppm install HTML::TreeBuilder::XPath
call ppm install JSON
call ppm install JSON::Any
call ppm install JSON::XS
call ppm install List::MoreUtils
call ppm install Math::Big
call ppm install Math::Big::Factors
call ppm install Module::Build
call ppm install Module::Install
call ppm install Module::Install::AuthorTests
call ppm install Module::Install::ExtraTests
call ppm install Module::Starter
call ppm install Moose
call ppm install MooseX::App::Cmd
call ppm install MooseX::Method::Signatures
call ppm install MooseX::Types::Common
call ppm install MooseX::Types::DateTimeX
call ppm install MooseX::Types::Structured
call ppm install Net::CIDR::Lite
call ppm install Net::DNS
call ppm install Net::IP
call ppm install Net::Netmask
call ppm install Net::Ping
call ppm install Perl::Critic
call ppm install Readonly::XS
call ppm install Regexp::Common
call ppm install Spreadsheet::ParseExcel
call ppm install Spreadsheet::Read
call ppm install Spreadsheet::WriteExcel
call ppm install Test::Most
call ppm install Test::Perl::Critic
call ppm install Test::Pod
call ppm install Test::Pod::Coverage
call ppm install Text::CSV_XS
call ppm install Try::Tiny
call ppm install YAML
call ppm install YAML::Any
call ppm install YAML::Syck
call ppm install YAML::XS
call ppm install autodie
call ppm install namespace::autoclean
